services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${PG_ROOT_USER}"
      POSTGRES_PASSWORD: "${PG_ROOT_PASSWORD}"
      POSTGRES_DB: "${PG_DATABASE}"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5432:5432"

  web:
    build:
      context: .
    restart: always
    environment:
      PG_USER: "${PG_USER}"
      PG_PASSWORD: "${PG_PASSWORD}"
      PG_HOST: "${PG_HOST}"
      PG_DATABASE: "${PG_DATABASE}"
    ports:
      - "0.0.0.0:8001:8001"
    depends_on:
      - db
#volumes:
#  postgres_data:
