services:
  advanced_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://root:example@mongo:27017/"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
